### ISSUE TITLE
stochastique dans la fonction puits?

### ISSUE THREAD

**Issue by torsteed** [hathas07/FUNS#1]
Bonjour,
Dans la fonction puits, il serait intéressant de vérifier que la matrice passée en argument est bien stochastique.
On pourrait effectuer cela en modifiant `if P[i,i]==1:` par ` if P[i,i]==1 and stochastique(P):`
Bien à vous...

**Comment by hathas07** [comment]
> Bonjour,
> Dans la fonction puits, il serait intéressant de vérifier que la matrice passée en argument est bien stochastique.
> On pourrait effectuer cela en modifiant `if P[i,i]==1:` par ` if P[i,i]==1 and stochastique(P):`
> Bien à vous...

En effet c'est un ajout intéressant, il sera effectuer dans la prochaine mise à jour
Cordialement

**Comment by torsteed** [comment]
Le projet est terminé
